name: "systex"
version: 0.3.4
github: "rik-tools/systex"
license: "GPL-3"
license-file: "etc/license"
author: "Rik Howard"
maintainer: "rik@rik-howard.info"
copyright: "2024 Rik Howard"
synopsis: "Systex is a collection of utility libraries."
description: "Systex provides some extensions to the base libraries."
category: "Experimental"

extra-doc-files:
- readme.md
- artisan.md
- builder.md
- changes.md

dependencies:
- base >= 4.7 && < 5
- split >= 0.2.5 && < 0.3
- neat-interpolation >= 0.5.1.4 && < 0.5.2
- text >= 2.1.1 && < 2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing

library:
  source-dirs: src
  dependencies:
    - directory >= 1.3.8.5 && < 1.4
    - unix >= 2.8.6.0 && < 2.9
    - regex-tdfa >= 1.3.2.2 && < 1.4
    - yjtools >= 0.9.18 && < 1.0

tests:
  systex-test:
    main: Test.hs
    source-dirs: tst
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - systex
    - HUnit

