#!/bin/bash
##
# $ diva check
##

echo -n "Diva is checking"
diva unpack &>/o

if ! stack runhaskell usr/use-filer &>/tmp/diva-check
then code=120; diva repack &>/o; echo ': filer error!'; exit $code
fi

cp var/original.md /tmp
if ! stack runhaskell usr/use-markdown &>/tmp/diva-check
then code=121; diva repack &>/o; echo ': markdown error!'; exit $code
fi

diva repack &>/o; echo .

