#!/bin/bash
##
# $ diva test
##

echo -n "Diva is testing"
cp var/original.md /tmp
diva unpack &>/o

if stack test  &>/tmp/diva-test
then diva repack &>/o
else code=$? diva repack &>/o; echo '!'; exit $code
fi

if test "$(cat /tmp/original.md)" == "$(cat /tmp/actual.md)"
then echo .
else
    echo '!'
    echo "error: in /tmp, actual.md != original.md" >/tmp/diva-test
    exit 122
fi

