#!/bin/bash
##
# $ diva show update
##
source ~/.diva/mod/tui
source .diva/mod/truth
source .diva/mod/update
diva repack &>/o

nodent ""
nodent "Diva Update: $PWD"
nodent ""
indent "modes:"
dudent "folders: $(folders)"
dudent "scripts: $(scripts)"
dudent "modules: $(modules)"
nodent ""
indent "versions:"
dudent "changes: $(version)"
dudent "package: $(package_version)"
dudent "string : $(string_version)"
#dudent "usage  : $(usage_version)"
nodent ""
indent "hacker:"
dudent "artisan: $(artisan_stamp)"
dudent "source : $(source_stamp)"
dudent "testing: $(testing_stamp)"
nodent ""
indent "tester:"
dudent "uts imp/fin: $(ut_imps)/$(ut_fins)"
dudent "its imp/fin: $(it_imps)/$(it_fins)"
nodent ""

